name: release

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4


      - uses: garnet-org/action@v2
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}